name = "steakfinder"
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"

[env.production]
name = "steakfinder"

[env.preview]
name = "steakfinder-preview"

# Environment variables are managed as secrets via:
# wrangler pages secret put NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
